# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: author

# A list of assignees, overrides reviewers if set
reviewers:
  - bjohnsto
  - jochapma
  - jshimkus-rh

# A number of reviewers to add to the pull request
# Set to 0 to add all of the reviewers.
# Uses numberOfReviewers if unset.
numberOfReviewers: 0

# A number of assignees to add to the pull request
# Set to 0 to add all of the assignees.
# Uses numberOfReviewers if unset.
numberOfAssignees: 0
